build:
  environment:
    postgresql: false
    redis: false
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override:
          - php-scrutinizer-run
          - command: phpcs-run
            use_website_config: true
          - command: vendor/bin/phpmd --reportfile /tmp/phpmd.xml
            analysis:
              file: /tmp/phpmd.xml
              format: general-checkstyle
    php54:
      environment:
        php: 5.4
    php70:
      environment:
        php: 7.0
    php71:
      environment:
        php: 7.1

checks:
  php: true

filter:
  excluded_paths:
    - tests/*